### ISSUE TITLE
Idea: Make the tablet verison of the 2012 player appear when on mobile.

### ISSUE THREAD

**Issue by Cattskit** [cosmixcode/revtube#12]
Possibe mobile support. Check embed.php for how to enable it.

**Comment by Cattskit** [comment]
Closed due to Risk removing the 2012 player.

**Comment by ky-1** [comment]
how are you gonna make it. Work in chrome

**Comment by ky-1** [comment]
2012 player is fucked in chromium browsers and only works in firefox

**Comment by ky-1** [comment]
im not sure

**Comment by ky-1** [comment]
Okay!
